# Generated by Django 5.2.8 on 2025-12-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10)),
                ('descripcion', models.TextField()),
                ('zona', models.CharField(max_length=100)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
